version: '3.7'

services:
  db_dev:
    image: postgres:11
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    command: -c 'config_file=/etc/postgresql.conf'
    configs:
      - source: postgres
        target: /etc/postgresql.conf
      - source: airflow_init
        target: /docker-entrypoint-initdb.d/1_create_user_db.sh
    ports:
      - 5432:5432
    extra_hosts:
      - "v4:10.80.0.5"
    networks:
      - dev_network
    environment:
      POSTGRES_USER: 'hub'
      POSTGRES_PASSWORD: '1qaz2wsx'
      POSTGRES_DB: 'hub'
    volumes:
      - /var/nfs/configs/postgres/pgdata:/var/lib/postgresql/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/nfs/logs/postgres:/var/lib/postgresql/pg_log

networks:
  dev_network:

configs:
  postgres:
   file: /var/nfs/configs/postgres/postgresql.conf
  airflow_init:
   file: /var/nfs/configs/postgres/1_create_user_db.sh
